"""Audit job repository port."""

from collections.abc import Mapping
from typing import Any, Protocol


class AuditJobRepositoryPort(Protocol):
    def create(self, job_id: str, request: Mapping[str, Any]) -> None: ...
    def mark_running(self, job_id: str) -> None: ...
    def complete(self, job_id: str, result: Mapping[str, Any]) -> None: ...
    def fail(self, job_id: str, error: str) -> None: ...
